config/routes.rb
Rails.application.routes.draw do
  get 'auth/redbooth/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'

  root 'welcome#index'
  resources :projects do
    resources :task_lists
  end
end

app/models/task_list.rb
class TaskList
  include ActiveModel::Model

  attr_accessor :project_id, :name
  validates :name, presence: true

  def to_provider
    as_json.symbolize_keys
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |u|
      u.provider = auth.provider
      u.uid = auth.uid
      u.name = auth.info.name
      u.email = auth.info.email
      u.oauth_token = auth.credentials.token
      u.oauth_refresh_token = auth.credentials.refresh_token
      u.oauth_expires_at = Time.at(auth.credentials.expires_at)
      u.save!
    end
  end

  def oauth_expired?
    Time.current > oauth_expires_at
  end
end

app/controllers/application_controller.rb
require 'redbooth_on_rails/service'

class ApplicationController < ActionController::Base
  include RedboothOnRails::Service

  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate
    redirect_to root_url unless logged_in?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate

  def index
    @projects = redbooth.project.all
  end

  def show
    @project = redbooth.project.find(project_id)
    @task_lists = redbooth.task_list.all(project_id: project_id)
  end

  private

  def project_id
    @project_id ||= params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_filter :authenticate

  def new
    @task_list = TaskList.new(project_id: params[:project_id])
  end

  def create
    @task_list = TaskList.new(task_list_params)
    if @task_list.valid?
      redbooth.task_list.create(@task_list.to_provider)
      redirect_to project_path(project_id), notice: t('flash.task_lists.created')
    else
      flash.now[:error] = t('flash.form.validation_errors')
      render :new
    end
  end

  private

  def task_list_params
    params.slice(:project_id).merge(params[:task_list])
  end

  def project_id
    @project_id ||= params[:project_id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to :projects if logged_in?
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  def bootstrap_class_for(type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }.fetch(type, type.to_s)
  end

  def flash_message(type, msg)
    content_tag :div, class: "alert #{bootstrap_class_for(type.to_sym)}" do
      concat flash_close_button
      concat msg
    end
  end

  def flash_close_button
    content_tag(:button, class: 'close', data: { dismiss: 'alert' }) { '×' }
  end

  def title(i18nt, params = {})
    content_tag(:h2) { t("controllers.#{i18nt}.title", params) }
  end

  def default_description
    content_tag(:em, class: 'text-muted') { t('helpers.default_description') }
  end

  def description(description)
    text = description.present? ? description : default_description
    text.html_safe
  end

  def created_on(datetime)
    t('helpers.created_on', datetime: Time.at(datetime).strftime('%c'))
  end

  def glyphicon(icon_name)
    content_tag(:span, class: "glyphicon glyphicon-#{icon_name}") { '' }
  end

  def link_to_login(options = {})
    text = "#{glyphicon('user')} #{t('helpers.login_with')} Redbooth".html_safe
    link_to(text, '/auth/redbooth', options)
  end

  def link_to_logout
    text =
      "#{t('helpers.logout')} <b>#{current_user.name}</b> #{glyphicon('log-out')}".html_safe
    link_to(text, sign_out_path)
  end

  def btn_link_to(text, path, options = {})
    options_class = options.delete(:class) || ''
    opts = { class: "#{options_class} btn btn-primary" }
    link_to text, path, options.merge(opts)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RedboothOnRails
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .row
          #menu.col-md-8
            = render 'shared/menu'
          #user.col-md-4
            = render 'shared/user'

    .container
      .row
        .col-md-12
          = render 'shared/flash'
          = yield

app/views/projects/index.html.haml
= title('projects.index')

- @projects.each do |project|
  %div.panel.panel-default
    %div.panel-heading
      = link_to(glyphicon('tasks'), project_path(project.id), class: 'pull-right')
      %h4.panel-title.clearfix
        = project.name
    %div.panel-body
      = description(project.description)
    %div.panel-footer
      %small.pull-right
        = created_on(project.created_at)
      = btn_link_to 'Add task list', new_project_task_list_path(project.id)

app/views/projects/show.html.haml
= title('projects.show', name: @project.name)

%ul.list-group-item
  - @task_lists.each do |task_list|
    %li.list-group-item
      %h5.list-group-item-heading
        = task_list.name

%span.pull-right
  = btn_link_to '+', new_project_task_list_path(@project.id)

app/views/shared/_flash.html.haml
- flash.each do |type, msg|
  = flash_message(type, msg)

app/views/shared/_menu.html.haml
.navbar-header
  = link_to('RedboothOnRails', root_url, class: 'navbar-brand')
- if logged_in?
  %ul.nav.navbar-nav
    %li
      = link_to(t('controllers.projects.index.title'), projects_path)

app/views/shared/_user.html.haml
%ul.nav.navbar-nav.navbar-right
  %li
    - if logged_in?
      = link_to_logout
    - else
      = link_to_login

app/views/task_lists/new.html.haml
= title('task_lists.create')

= simple_form_for [:project, @task_list] do |f|
  = f.input :name
  = f.button :submit

app/views/welcome/index.html.haml
%hr
.container
  .row
    .col-md-12
      .jumbotron
        %h1
          = t('controllers.welcome.title')
        %p
          = t('controllers.welcome.content')
        %p
          = link_to_login(class: 'btn btn-primary btn-lg', role: 'button')